# Generated by Django 2.2.13 on 2021-08-27 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='status',
            field=models.CharField(blank=True, choices=[('unpaid', 'unpaid'), ('partial', 'partial'), ('completed', 'completed')], max_length=32, null=True),
        ),
    ]
