# Generated by Django 2.2.13 on 2021-08-27 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0002_auto_20210827_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('cheque', 'cheque'), ('credit', 'credit'), ('debit', 'debit')], max_length=32, null=True),
        ),
    ]
