# Generated by Django 2.2.13 on 2021-08-28 06:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ra.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
        ('crm', '0003_remove_customer_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0004_auto_20210827_1039'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='refer code')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='value')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date and time')),
                ('lastmod', models.DateTimeField(db_index=True, verbose_name='last modification')),
                ('customer', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('unpaid', 'unpaid'), ('partial', 'partial'), ('completed', 'completed')], max_length=32, null=True)),
                ('percent_per_month', models.DecimalField(decimal_places=2, max_digits=5, null=True)),
                ('amount_left', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('cheque', 'cheque'), ('credit', 'credit'), ('debit', 'debit')], max_length=32, null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_transaction_employee', to='hr.Employee')),
                ('lastmod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_newexpensetransaction_lastmod_related', to=settings.AUTH_USER_MODEL, verbose_name='last modification by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_newexpensetransaction_related', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
                ('sponsor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='daily_transaction_sponsor', to='crm.Customer')),
            ],
            options={
                'verbose_name': 'Daily Transaction',
                'verbose_name_plural': 'Daily Transactions',
            },
            bases=(ra.base.models.DiffingMixin, models.Model),
        ),
    ]
