# Generated by Django 2.2.13 on 2021-08-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0005_newexpensetransaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newexpensetransaction',
            name='amount_left',
        ),
        migrations.RemoveField(
            model_name='newexpensetransaction',
            name='percent_per_month',
        ),
        migrations.RemoveField(
            model_name='newexpensetransaction',
            name='sponsor',
        ),
        migrations.RemoveField(
            model_name='newexpensetransaction',
            name='status',
        ),
    ]
