# Generated by Django 2.2.13 on 2021-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0006_auto_20210828_0608'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
