# Generated by Django 2.2.13 on 2021-08-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('general', '0008_auto_20210831_1600'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newexpensetransaction',
            old_name='customer_account',
            new_name='account',
        ),
    ]
