# Generated by Django 2.2.13 on 2021-09-07 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ra.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20210831_1620'),
        ('hr', '0002_auto_20210831_1620'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('general', '0010_auto_20210907_1122'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewExpenseTransaction1',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='refer code')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value INR')),
                ('value1', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Value USD')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date and time')),
                ('lastmod', models.DateTimeField(db_index=True, verbose_name='last modification')),
                ('customer', models.CharField(blank=True, max_length=256, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_customer', to='crm.Customer')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='withdrawal_employee', to='hr.Employee')),
                ('lastmod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_newexpensetransaction1_lastmod_related', to=settings.AUTH_USER_MODEL, verbose_name='last modification by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_newexpensetransaction1_related', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Withdrawal',
                'verbose_name_plural': 'Withdrawals',
            },
            bases=(ra.base.models.DiffingMixin, models.Model),
        ),
    ]
