# Generated by Django 2.2.13 on 2021-08-31 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_customer_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={'verbose_name': 'Account', 'verbose_name_plural': 'Accounts'},
        ),
    ]
