# Generated by Django 2.2.13 on 2021-08-31 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_auto_20210831_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(blank=True, help_text='For fast recall', verbose_name='Identifier slug'),
        ),
    ]
