# Generated by Django 2.2.13 on 2021-08-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dholera', '0002_auto_20210805_0750'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='warehousemanager',
            name='location',
        ),
        migrations.RemoveField(
            model_name='warehousemanager',
            name='manager',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Project', 'verbose_name_plural': 'Projects'},
        ),
        migrations.RenameField(
            model_name='sale',
            old_name='seller',
            new_name='employee',
        ),
        migrations.RemoveField(
            model_name='category',
            name='parent_colony',
        ),
        migrations.RemoveField(
            model_name='item',
            name='location',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='customer',
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='WareHouse',
        ),
        migrations.DeleteModel(
            name='WareHouseManager',
        ),
    ]
