# Generated by Django 2.2.13 on 2021-08-27 13:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import ra.base.models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_customer_user'),
        ('hr', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dholera', '0003_auto_20210827_0941'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseTransaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(blank=True, verbose_name='refer code')),
                ('doc_date', models.DateTimeField(db_index=True, verbose_name='date')),
                ('doc_type', models.CharField(db_index=True, max_length=30)),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('value', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='value')),
                ('creation_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='creation date and time')),
                ('lastmod', models.DateTimeField(db_index=True, verbose_name='last modification')),
                ('customer', models.CharField(blank=True, max_length=256, null=True)),
                ('status', models.CharField(blank=True, choices=[('unpaid', 'unpaid'), ('partial', 'partial'), ('completed', 'completed')], max_length=32, null=True)),
                ('amount_left', models.IntegerField(default=0)),
                ('type', models.CharField(blank=True, choices=[('cheque', 'cheque'), ('credit', 'credit'), ('debit', 'debit')], max_length=32, null=True)),
                ('plot_number', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dholera_transaction_employee', to='hr.Employee')),
                ('lastmod_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dholera_expensetransaction_lastmod_related', to=settings.AUTH_USER_MODEL, verbose_name='last modification by')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dholera_expensetransaction_related', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'Dholera Transaction',
                'verbose_name_plural': 'Dholera Transactions',
            },
            bases=(ra.base.models.DiffingMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='sale',
            name='employee',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='lastmod_user',
        ),
        migrations.RemoveField(
            model_name='sale',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saleproducts',
            name='lastmod_user',
        ),
        migrations.RemoveField(
            model_name='saleproducts',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='saleproducts',
            name='plot',
        ),
        migrations.RemoveField(
            model_name='saleproducts',
            name='sale',
        ),
        migrations.AddField(
            model_name='category',
            name='total_plots',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='Item',
        ),
        migrations.DeleteModel(
            name='Sale',
        ),
        migrations.DeleteModel(
            name='SaleProducts',
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dholera.Category'),
        ),
        migrations.AddField(
            model_name='expensetransaction',
            name='sponsor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dholera_transaction_sponsor', to='crm.Customer'),
        ),
    ]
