# Generated by Django 2.2 on 2021-08-05 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleproducts',
            name='roi',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='sale',
            name='status',
            field=models.CharField(blank=True, choices=[('order_submitted', 'order_submitted'), ('roi started', 'roi started'), ('completed', 'completed')], max_length=32),
        ),
    ]
