# Generated by Django 2.2.13 on 2021-08-27 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0003_auto_20210827_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='customer',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
