# Generated by Django 2.2.13 on 2021-08-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0004_auto_20210827_1034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='percent_per_month',
            field=models.DecimalField(decimal_places=2, max_digits=5, null=True),
        ),
    ]
