# Generated by Django 2.2.13 on 2021-08-30 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0007_expensetransaction_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='account_number',
            field=models.CharField(max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='account_type',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
