# Generated by Django 2.2.13 on 2021-08-31 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0008_auto_20210830_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='account_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='expensetransaction',
            name='account_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
