# Generated by Django 2.2.13 on 2021-09-03 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0010_expensetransaction_customer_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensetransaction',
            name='type',
            field=models.CharField(blank=True, choices=[('cheque', 'cheque'), ('credit', 'deposit'), ('debit', 'withdraw')], max_length=32, null=True),
        ),
    ]
