# Generated by Django 2.2.13 on 2021-08-31 16:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0003_remove_customer_user'),
        ('ipaymatics', '0003_auto_20210827_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='expensetransaction',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ipaymatics_transaction_customer', to='crm.Customer'),
        ),
    ]
